version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "0:0"
    depends_on:
      - main
      - exp

  main:
    build: ./backend
    container_name: main
    environment:
      - FLASK_APP=main_server.py
    volumes:
      - ./backend:/app  # Asegura que los archivos sean accesibles

  exp:
    build: ./backend_exp
    container_name: exp
    environment:
      - FLASK_APP=exp_server.py
    volumes:
      - ./backend:/app  # Asegura que los archivos sean accesibles